-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDeRcJTBh
6VsHlIpbEaZ31NAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIKfsSiK+UB/S5vx+
0KnxotFMI1PwOc6jhFbdwY+MXjehAAAAsCon2+2/z5UCfGG5o2z0K2qpOnYLdNm3Gsg1a8
8er9PW3Q48KHTfwQfbCJ4odzdg+cDpdFPLF+fwdSXlWkjU2A+tYDQBkAGTeUWt+E7NqtOn
uuXedLCs/jabMfnWXq+kpvlqRgJUkUDxpxQqNuUhEp+xbeAUu9W2M/ys+OLKoypb1J1M/C
8dBH1RtAli89MZwj4RJpXJ3HmpfZqTbWvR/iD8TGmIEjj3QpPUziqvrX7I
-----END OPENSSH PRIVATE KEY-----
